### Data set (load, normalize, train and test)

In [1]:
import numpy as np 
import pandas as pd

df = pd.read_excel('Dataset1.xls')

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1632 entries, 0 to 1631
Data columns (total 29 columns):
No                       1630 non-null float64
SMILES-Adenot            1629 non-null object
SMILES                   1627 non-null object
SMILES-B                 1601 non-null object
Name                     1631 non-null object
BBB-crossing             1630 non-null object
P-gp                     88 non-null object
note                     154 non-null object
E                        1601 non-null float64
S                        1601 non-null float64
A                        1601 non-null float64
B                        1601 non-null float64
V                        1601 non-null float64
MW                       1601 non-null float64
PSA                      1601 non-null float64
logP                     1601 non-null float64
logD(7.4)                1593 non-null float64
No of H donors           1601 non-null float64
No of H Accetors         1601 non-null float64
pKa (Acid)

In [3]:
df.head()

No                                      SMILES-Adenot  \
0  1.0                                 FC(F)(Cl)C(F)(F)Cl   
1  2.0                         CC1CCCCC1(N1CCCCC1)c1sccc1   
2  3.0          CC(Cc1ccccc1)NCCn1cnc2c1C(=O)N(C)C(=O)N2C   
3  4.0                 CC(=O)NCCCN1CCN(CC1)c1cc(ccc1Cl)Cl   
4  5.0  CC(C)CCC[C@@H](C)[C@H]1CCC2C3C[C@@H](Br)[C@@]4...   

                                              SMILES  \
0                                 FC(F)(Cl)C(F)(F)Cl   
1                         CC1CCCCC1(N1CCCCC1)c1sccc1   
2        CC(Cc1ccccc1)NCCn2cnc3n(C)c(=O)n(C)c(=O)c23   
3                CC(=O)NCCCN1CCN(CC1)c2cc(Cl)ccc2Cl    
4  CC(C)CCCC(C)C3CCC4C2CC(Br)C1(Br)CC(CCC1(C)C2CC...   

                                            SMILES-B  \
0                                 FC(F)(Cl)C(F)(F)Cl   
1                         CC1CCCCC1(N1CCCCC1)c1sccc1   
2        CC(Cc1ccccc1)NCCn2cnc3n(C)c(=O)n(C)c(=O)c23   
3                CC(=O)NCCCN1CCN(CC1)c2cc(Cl)ccc2Cl    
4  CC(C)CCCC(C)C3CCC4C2CC(Br)C1(Br)CC(CCC1(C)C2CC...   

                                          Name BBB-crossing P-gp  \
0   12dichlorotetrafluoroethane (cryofluorane)            1  NaN   
1       2methylthiophencyclidine (gacyclidine)            1  NaN   
2  7amphetaminoethyltheophylline (fenetylline)            1  NaN   
3                                   acaprazine            1  NaN   
4                                   acebrochol            1  NaN   

                        note         E         S  ...  pKa (Acid)  pKa (Base)  \
0  Adenot names cryofluorane -0.071273  0.106541  ...       999.0      -999.0   
1   adenot names gacyclidine  1.376874  1.113330  ...       999.0         8.5   
2   Adenot names fenetylline  2.200494  2.769513  ...       999.0         8.9   
3                        NaN  1.664719  2.202124  ...       999.0         7.6   
4                        NaN  1.855738  2.195813  ...       999.0      -999.0   

   Iv (Carboxy)   (+)Form  (-)Form  (+/-)Form     0Form  \
0           0.0  0.000000      0.0        0.0  1.000000   
1           0.0  0.926412      0.0        0.0  0.073588   
2           0.0  0.969347      0.0        0.0  0.030653   
3           0.0  0.613137      0.0        0.0  0.386863   
4           0.0  0.000000      0.0        0.0  1.000000   

   No of Rotatable bonds  Distance-Ab  Training or test set  
0                    1.0     0.261317              Training  
1                    2.0     0.294440              Training  
2                    6.0     0.427647              Training  
3                    5.0     0.276987              Training  
4                    7.0     0.758228              Training  

[5 rows x 29 columns]

In [5]:
df.columns[8:27]

Index(['E', 'S', 'A', 'B', 'V', 'MW', 'PSA', 'logP', 'logD(7.4)',
       'No of H donors', 'No of H Accetors', 'pKa (Acid)', 'pKa (Base)',
       'Iv (Carboxy)', '(+)Form', '(-)Form', '(+/-)Form', '0Form',
       'No of Rotatable bonds'],
      dtype='object')

### Using the training and testing set provided in the dataset

In [13]:
data = df.iloc[0:1593, 8:27]
target = df.iloc[0:1593, 5]
target = target.astype('int')
target

0       1
1       1
2       1
3       1
4       1
5       1
6       1
7       1
8       1
9       1
10      1
11      1
12      1
13      1
14      1
15      1
16      1
17      1
18      1
19      1
20      1
21      1
22      1
23      1
24      1
25      1
26      1
27      1
28      1
29      1
       ..
1563    0
1564    0
1565    0
1566    0
1567    0
1568    0
1569    0
1570    0
1571    0
1572    0
1573    0
1574    0
1575    0
1576    0
1577    0
1578    0
1579    0
1580    0
1581    0
1582    0
1583    0
1584    0
1585    0
1586    0
1587    0
1588    0
1589    0
1590    0
1591    0
1592    0
Name: BBB-crossing, Length: 1593, dtype: int32

In [10]:
x_train = data.iloc[0:1093, 0:18]
x_train1 = np.array(x_train)
print(x_train.shape)
print(x_train1.shape)

(1093, 18)
(1093, 18)


In [14]:
y_train = target.iloc[0:1093]
y_train1 = np.array(y_train)
y_train1 = y_train1.astype('int')
print(y_train.shape)
print(y_train1.shape)

(1093,)
(1093,)


In [15]:
x_test = data.iloc[1094:1594, 0:18]
x_test1 = np.array(x_test)
print(x_test.shape)
print(x_test1.shape)

(499, 18)
(499, 18)


In [16]:
y_test = target.iloc[1094:1593]
y_test1 = np.array(y_test)
y_test1 = y_test1.astype('int')
print(y_test.shape)
print(y_test1.shape)

(499,)
(499,)


### SVM Model

In [17]:
from sklearn.svm import SVC
import time

In [18]:
model = SVC(kernel = 'rbf', gamma = 'auto', )

In [19]:
t0=time.time()
model.fit(x_train1, y_train1)
print("training time:", round(time.time()-t0, 3), "s")

training time: 0.086 s


In [20]:
t1=time.time()
pred = model.predict(x_test1)
print("predict time:", round(time.time()-t1, 3), "s")

predict time: 0.03 s


In [21]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [22]:
print(accuracy_score(y_test1, pred))

0.9158316633266533


In [23]:
print(confusion_matrix(y_test1, pred))

[[  8  41]
 [  1 449]]


In [24]:
print(classification_report(y_test1, pred))

              precision    recall  f1-score   support

           0       0.89      0.16      0.28        49
           1       0.92      1.00      0.96       450

    accuracy                           0.92       499
   macro avg       0.90      0.58      0.62       499
weighted avg       0.91      0.92      0.89       499



### Choosing 40% of dataset as testing, and randomizing the dataset

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(data, target, test_size=0.4, random_state=0)

Y_train = Y_train.astype('int')
Y_test = Y_test.astype('int')

In [26]:
Y_test.unique()

array([0, 1], dtype=int64)

In [27]:
X_test.shape, Y_test.shape

((638, 19), (638,))

In [28]:
t0=time.time()
model.fit(X_train, Y_train)
print("training time:", round(time.time()-t0, 3), "s")

training time: 0.067 s


In [29]:
t1=time.time()
pred = model.predict(X_test)
print("predict time:", round(time.time()-t1, 3), "s")

predict time: 0.036 s


In [30]:
print(accuracy_score(Y_test, pred))

0.8244514106583072


### Cross Validation

In [31]:
from sklearn.model_selection import cross_val_score

cv_results = cross_val_score(model, data, target, cv=10)

cv_results


array([0.80625   , 0.8125    , 0.8125    , 0.81761006, 0.81761006,
       0.81761006, 0.81761006, 0.81132075, 0.82389937, 0.82389937])

In [32]:
print("Accuracy: %0.2f (+/- %0.2f)" % (cv_results.mean(), cv_results.std() * 2))

Accuracy: 0.82 (+/- 0.01)
